/// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbjwq01wMFLC5zifTjbMRt516iKe6DQU',
    appId: '1:625932939860:web:9ada544aed85c9e670f3c1',
    messagingSenderId: '625932939860',
    projectId: 'perfectscheduler-37187',
    authDomain: 'perfectscheduler-37187.firebaseapp.com',
    storageBucket: 'perfectscheduler-37187.appspot.com',
    measurementId: 'G-XS20M006ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1OdW2QXtcl1x9Pt0hyYq8Xo9F_EIRzs',
    appId: '1:625932939860:android:e1775f3ae0fc5fbd70f3c1',
    messagingSenderId: '625932939860',
    projectId: 'perfectscheduler-37187',
    storageBucket: 'perfectscheduler-37187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJaKw7s-Z7mAs21vzdXK0oPPSxvAODlBs',
    appId: '1:625932939860:ios:4a73492063add54870f3c1',
    messagingSenderId: '625932939860',
    projectId: 'perfectscheduler-37187',
    storageBucket: 'perfectscheduler-37187.appspot.com',
    iosClientId: '625932939860-vb4ja9lde8kkttr1j9ojo9f2hv4tokeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJaKw7s-Z7mAs21vzdXK0oPPSxvAODlBs',
    appId: '1:625932939860:ios:4a73492063add54870f3c1',
    messagingSenderId: '625932939860',
    projectId: 'perfectscheduler-37187',
    storageBucket: 'perfectscheduler-37187.appspot.com',
    iosClientId: '625932939860-vb4ja9lde8kkttr1j9ojo9f2hv4tokeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectScheduler',
  );
}
