// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLF-OjDMMASochp0H7tOVOv-ZYLKtT9Lg',
    appId: '1:157652711331:web:6a2cf5c4c5a8224b464c16',
    messagingSenderId: '157652711331',
    projectId: 'login-896bd',
    authDomain: 'login-896bd.firebaseapp.com',
    storageBucket: 'login-896bd.appspot.com',
    measurementId: 'G-68826LYMPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMf8Kh9P1Mzf0BshMWvowj1K1iTTdYKLA',
    appId: '1:157652711331:android:ed04b33a7900abdc464c16',
    messagingSenderId: '157652711331',
    projectId: 'login-896bd',
    storageBucket: 'login-896bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabnvDBwmQxSoNBkmEVMMasCmNM-pHFzo',
    appId: '1:157652711331:ios:2ae9438a66ba7c32464c16',
    messagingSenderId: '157652711331',
    projectId: 'login-896bd',
    storageBucket: 'login-896bd.appspot.com',
    iosClientId: '157652711331-jdne7svms1gh189hnle5ng300c72huv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabnvDBwmQxSoNBkmEVMMasCmNM-pHFzo',
    appId: '1:157652711331:ios:2ae9438a66ba7c32464c16',
    messagingSenderId: '157652711331',
    projectId: 'login-896bd',
    storageBucket: 'login-896bd.appspot.com',
    iosClientId: '157652711331-jdne7svms1gh189hnle5ng300c72huv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectScheduler',
  );
}
